### ISSUE TITLE
スクレイピング先をサウナイキタイから変更する

### ISSUE THREAD

**Issue by siida36** [asaka2-alb/smart-sauna-map-back#25]
## 背景

- アルファ版では動作確認のためにスクレイピングのソースにサウナイキタイを使用しているが、本来は禁止されている

## 目的

- ベータ版をリリースするため、ソースをサウナイキタイからスクレイピングを禁止していないところへ変更する

## TODO

- [ ] どの関数を変更すればいいかを調べる
- [ ] 既存の処理のテスト疎通を確認する
- [ ] どのような変更をすればいいかを決定する
- [ ] 新たなスクレイピング先を選定する
- [ ] スクレイピング処理を実装する
- [ ] テストを通す

**Comment by siida36** [comment]
## 5/1 進捗

### `search_sauna()`を抽象化する

処理が結構複雑なので、SaunaIkitaiScraperとでも切り出すことにする。

- [x] scraperディレクトリを作成する
- [x] sauna_ikitai_scraper.pyにSaunaIkitaiScraperを切り出す
  - [x] sauna.pyにSaunaを切り出す
  - [x] room.pyに各種Roomを切り出す
- [x] 元のsearch_sauna()からScraperを呼び出すように修正する
- [ ] abstract_scraper.pyにAbstractScraperを作成する
- [ ] 既存のpytestを通す
- [ ] google_map_scraper.pyにGoogleMapScraperを作成する

### `_request()`において、見に行くページをGoogleMapのレビューにする

- [x] 何を使うかを決める
  - [プレイス ライブラリ](https://developers.google.com/maps/documentation/javascript/places?hl=ja)
- [ ] APIを有効にする
- [ ] APIの入出力を確認する
- [ ] 元の仕様の入出力を確認する

**Comment by siida36** [comment]
一旦動かせた。イキタイbが星の平均値？になってしまったので、そこは要検討
<img width="1021" alt="スクリーンショット 2023-05-02 17 38 24" src="https://user-images.githubusercontent.com/36360393/235619495-eab70d83-7e65-41d7-99cf-7cf3803d9a66.png">

**Comment by siida36** [comment]
まだローカルでしか動かしてないけどめっちゃ早くレスポンスかえってくる
やっぱGoogleすごいわ
